title: Ethan Mason's Blog
description: A blog about philosophy, computer science, and more 
baseurl: ""
url: "https://blog.masonethan.com"

# Build settings
markdown: kramdown
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - about.md
  - archive.md  

# Social links
github_username: e-mason03
