title: Ethan Mason's Blog
description: A blog about philosophy, computer science, and more 
baseurl: ""
url: "https://blog.masonethan.com"

# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
