title: Ethan Mason's Blog
description: A blog about philosophy, computer science, and more 
baseurl: ""
url: "https://blog.masonethan.com"

# Build settings
markdown: kramdown
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Navigation
header_pages:
  - about.md

# Social links
github_username: e-mason03
